### ISSUE TITLE
[bug] typescript import errors after updating from 5.5.0 to 6.0.2

### ISSUE THREAD

**Issue by JustFly1984** [fkhadra/react-toastify#472]
running `tsc --noEmit` results:

```
node_modules/react-toastify/dist/components/CloseButton.d.ts:1:8 - error TS1259: Module '"/project/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:64:1
    64 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/react-toastify/dist/components/Toast.d.ts:1:8 - error TS1259: Module '"/project/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:64:1
    64 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/react-toastify/dist/components/ToastContainer.d.ts:1:8 - error TS1259: Module '"/project/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:64:1
    64 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/react-toastify/dist/core/toast.d.ts:1:8 - error TS1259: Module '"/project/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:64:1
    64 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

<img width="1059" alt="Screenshot 2020-05-13 10 54 44" src="https://user-images.githubusercontent.com/2255993/81769636-4b127800-9508-11ea-99f5-8507ebc98f78.png">

We can't enable `esModuleInterop: true` for multiple reasons in our projects. @types/react should not be packed with module. Please build and publish next version with correct `import * as React from 'react'` and it will fix an issue for everybody.

**Comment by fkhadra** [comment]
Hey @JustFly1984, just published a new version can you tell me if it's ok for you now ?

**Comment by JustFly1984** [comment]
confirming that issues described above fixed, although new error described in https://github.com/fkhadra/react-toastify/issues/470 appeared

**Comment by fkhadra** [comment]
@JustFly1984 #470 fixed as well now
