### ISSUE TITLE
error ToastContainer after running `tsc` in command line

### ISSUE THREAD

**Issue by achmadk** [fkhadra/react-toastify#561]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
After upgrading `react-toastify` to v7.0.2, I execute `tsc` in command line. Unfortunately I got error message like this:

```sh
node_modules/react-toastify/dist/components/index.d.ts:3:15 - error TS2307: Cannot find module './ToastContainer' or its corresponding type declarations.

3 export * from './ToastContainer';
                ~~~~~~~~~~~~~~~~~~

node_modules/react-toastify/dist/index.d.ts:3:10 - error TS2305: Module '"./components"' has no exported member 'ToastContainer'.

3 export { ToastContainer, Bounce, Flip, Slide, Zoom } from './components';
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
1. Create web app template with react and typescript
2. Import `ToastContainer` component, then use it into your app.
3. Check typescript checking with command `tsc`  

**What is the expected behavior?**
No error emit after execute `tsc`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am using react v17 and ubuntu OS.

**Comment by achmadk** [comment]
If you dont mind, please check [here](https://github.com/fkhadra/react-toastify/compare/master...achmadk:fix-issue-561) to resolve this issue.

**Comment by fkhadra** [comment]
Hello @achmadk,

I think that something is wrong with your setup. I've been using the library exclusively with typescript and I never had this issue.  
You can find below a working example with typescript using CRA
[![Edit relaxed-shadow-nwcn4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-shadow-nwcn4?fontsize=14&hidenavigation=1&theme=dark)

Maybe if you can share your `tsconfig.json` or reproduce the issue using codesanbox I could help.

**Comment by achmadk** [comment]
I have refresh install dependencies with yarn but still have same problem above.

[![Edit holy-cache-dddx8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/holy-cache-dddx8?fontsize=14&hidenavigation=1&theme=dark)

**Comment by felixmosh** [comment]
same in my projects, the `ToastContainer.d.ts` is missing in `node_modules`,

![image](https://user-images.githubusercontent.com/9304194/106454345-44130780-6493-11eb-9cdb-da4013bc9dea.png)

**Comment by fkhadra** [comment]
Thanks, @felixmosh that was helpful. TBH I don't even know how this happened. I've built it again and published a new version to npm.

**Comment by felixmosh** [comment]
@fkhadra I've just tested 7.0.3, same issue :|

**Comment by fkhadra** [comment]
@felixmosh can you delete node_modules/react-toastify ?
I've tried again on my side and I can see the typescript defintion
![Screen Shot 2021-02-01 at 1 04 45 PM](https://user-images.githubusercontent.com/5574267/106456689-25f6d880-648e-11eb-861e-9034ac576b5d.png)

Also, it has been packed when I ran npm publish
![Screen Shot 2021-02-01 at 1 05 38 PM](https://user-images.githubusercontent.com/5574267/106456704-3018d700-648e-11eb-93e2-75049497fc20.png)

**Comment by felixmosh** [comment]
Yeap, that helped, Thanx for the quick fix

**Comment by fkhadra** [comment]
@felixmosh you're welcome. cc @achmadk
